### ISSUE TITLE
Update references to BlockStressDefaults to new location for Create v6.0.0

### ISSUE THREAD

**Issue by BenPowellDev** [PssbleTrngle/CreateJetpack#149]
### What happened?

Update the reference to BlockStressDefaults to allow functionality with Create 6.0.0

Old Ref:
`com.simibubi.create.content.kinetics.BlockStressDefaults`

New Ref:
`com.simibubi.create.api.stress.BlockStressValues`

Mucho Gracias :)

### Loader

forge

### Mod Version

4.3.0

### Minecraft Version

1.20

### Relevant log output

```Shell

```

**Comment by PssbleTrngle** [comment]
Support for the newest create version will probably be released next weekend. Until then I will also have decided if I want to support 1.21 yet (just for anyone wondering and stumbling across this ticket)

**Comment by Seblor** [comment]
Hey there, just putting my feedback here since it seems relevant.

I really hope you can work on support for 1.21 (at least 1.21.1) since it's officially supported by Create 6. I know several server owners and modpack creators that waited for Create 6 to jump to 1.21.1.

I know we can't ask things of you since you are working on this for free on your own time, but for what it's worth, thank you for your work :)

**Comment by heyvito** [comment]
@PssbleTrngle In case you need a helping hand, I can try to port it to 1.21.1 in my spare time!
Saying that since I'm not sure whether you want help or want to decide that by yourself.

Just let me know! :)

**Comment by PssbleTrngle** [comment]
@heyvito thank you very much for your proposal, I don't think porting it to 1.21 will be a problem at all, it's just about maintaining multiple versions. In the past it definitely had a negative impact on my motivation, knowing that everything needed to be done for 3 forge and 2 fabric versions, which is why I might leave 1.21 out at first

**Comment by heyvito** [comment]
No problem at all! Let me know in case you need a helping hand at any
point! I'll love to assist!

Best wishes,
- Vito

**Comment by PssbleTrngle** [comment]
Fix for create 6.0.0 is out, I have also created a new issue for 1.21 support (#152), although that might have to wait a bit

**Comment by Joxos** [comment]
I am experiencing the same issue `java.lang.NoClassDefFoundError: com/simibubi/create/content/kinetics/BlockStressDefaults` on **Minecraft 1.20.1** with **Create Jetpack 4.3.0** and **Create 6.0.8.1+build.1744**.

It appears the error occurs because **Create 6.0 is now also available for 1.20.1**, but the mod version for 1.20.1 has not been updated to reflect this. The previous discussion seemed to focus on Create 6.0 for 1.21 only.

This should be a straightforward fix—simply updating the class reference to the new location (`com.simibubi.create.api.stress.BlockStressValues`). Could you please release an updated version of Create Jetpack for Minecraft 1.20.1?

Thank you once again for your excellent work and support!
